/**
 * Resource Manager API
 * The API of Resource Manager web application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface User {
    userID?: number;

    fullName?: string;

    email?: string;

    mobile?: string;

    enabled?: boolean;

    requests?: Array<models.Request>;

    userRole?: models.UserRole;

    cards?: Array<models.Card>;

}
