/**
 * Resource Manager API
 * The API of Resource Manager web application
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class ResourceTypeApi {
    protected basePath = 'http://localhost:8080/resource-manager-backend';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * Creates a resource type
     * Creates a resource type in the database
     * @param body
     */
    public resourcetypePost(body: models.ResourceType, extraHttpRequestParams?: any): Observable<number> {
        return this.resourcetypePostWithHttpInfo(body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Delete a resource type
     * Delete a resource type by resourcetypeID
     * @param resourcetypeID The identifier of the resource type to delete
     */
    public resourcetypeResourcetypeIDDelete(resourcetypeID: number, extraHttpRequestParams?: any): Observable<{}> {
        return this.resourcetypeResourcetypeIDDeleteWithHttpInfo(resourcetypeID, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Get a single resource type
     * Get a single resource type
     * @param resourcetypeID
     */
    public resourcetypeResourcetypeIDGet(resourcetypeID: number, extraHttpRequestParams?: any): Observable<models.ResourceType> {
        return this.resourcetypeResourcetypeIDGetWithHttpInfo(resourcetypeID, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Edit a resource type
     * Modify a resource type by handling all the fields and the identifier
     * @param resourcetypeID The identifier of the resource type to modify
     * @param body
     */
    public resourcetypeResourcetypeIDPut(resourcetypeID: number, body: models.ResourceType, extraHttpRequestParams?: any): Observable<number> {
        return this.resourcetypeResourcetypeIDPutWithHttpInfo(resourcetypeID, body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Get all resourceTypes
     * Get all resourceTypes
     */
    public resourcetypesGet(extraHttpRequestParams?: any): Observable<Array<models.ResourceType>> {
        return this.resourcetypesGetWithHttpInfo(extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }


    /**
     * Creates a resource type
     * Creates a resource type in the database
     * @param body
     */
    public resourcetypePostWithHttpInfo(body: models.ResourceType, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/resourcetype';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'body' is not null or undefined
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling resourcetypePost.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        // authentication (OauthSecurity) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Delete a resource type
     * Delete a resource type by resourcetypeID
     * @param resourcetypeID The identifier of the resource type to delete
     */
    public resourcetypeResourcetypeIDDeleteWithHttpInfo(resourcetypeID: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/resourcetype/${resourcetypeID}'
                    .replace('${' + 'resourcetypeID' + '}', String(resourcetypeID));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'resourcetypeID' is not null or undefined
        if (resourcetypeID === null || resourcetypeID === undefined) {
            throw new Error('Required parameter resourcetypeID was null or undefined when calling resourcetypeResourcetypeIDDelete.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        // authentication (OauthSecurity) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Get a single resource type
     * Get a single resource type
     * @param resourcetypeID
     */
    public resourcetypeResourcetypeIDGetWithHttpInfo(resourcetypeID: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/resourcetype/${resourcetypeID}'
                    .replace('${' + 'resourcetypeID' + '}', String(resourcetypeID));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'resourcetypeID' is not null or undefined
        if (resourcetypeID === null || resourcetypeID === undefined) {
            throw new Error('Required parameter resourcetypeID was null or undefined when calling resourcetypeResourcetypeIDGet.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Edit a resource type
     * Modify a resource type by handling all the fields and the identifier
     * @param resourcetypeID The identifier of the resource type to modify
     * @param body
     */
    public resourcetypeResourcetypeIDPutWithHttpInfo(resourcetypeID: number, body: models.ResourceType, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/resourcetype/${resourcetypeID}'
                    .replace('${' + 'resourcetypeID' + '}', String(resourcetypeID));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'resourcetypeID' is not null or undefined
        if (resourcetypeID === null || resourcetypeID === undefined) {
            throw new Error('Required parameter resourcetypeID was null or undefined when calling resourcetypeResourcetypeIDPut.');
        }
        // verify required parameter 'body' is not null or undefined
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling resourcetypeResourcetypeIDPut.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        // authentication (OauthSecurity) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Get all resourceTypes
     * Get all resourceTypes
     */
    public resourcetypesGetWithHttpInfo(extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/resourcetypes';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
